base_dir: "/tmp/sequreisp"
deploy_dir: "/tmp/sequreisp/deploy/current"
ppp_dir: "/tmp/ppp"
dhcpd_dir: "/tmp/dhcp3"
pingable_servers: "198.41.0.4 192.228.79.201 192.33.4.12 128.8.10.90 192.5.5.241 192.36.148.17"
ifb_up: "ifb0"
ifb_down: "ifb1"
ifb_ingress: "ifb2"
demo: false
tar_command: "tar"
